import Link from 'next/link';import {Photo} from '@/components/Photo';import {Booking} from '@/components/Booking';import {getPosts} from '@/lib/blog';import {site,menu} from '@/lib/site';
export default async function Home(){const posts=(await getPosts()).slice(0,3);return <><section className="hero"><div className="hero-image"><Photo kind="hero" label="ファーストビュー"/></div><div className="hero-copy"><p className="hero-kicker">OTSUKA / PRIVATE BEAUTY SALON</p><h1>肌にも、心にも、<br/><em>やさしい時間を。</em></h1><p>看護師オーナーが迎える、完全個室のFelice。<br/>大塚駅から徒歩1分、美容とリラクゼーションをあなたのペースで。</p><div className="hero-links"><a className="button dark" href={site.hotpepper} target="_blank" rel="noopener noreferrer">ご予約・メニューを見る <span>↗</span></a><a className="text-link" href={site.line} target="_blank" rel="noopener noreferrer">LINEで相談する ↗</a></div></div><span className="hero-side">FELICE — A MOMENT FOR YOURSELF</span></section>
<section className="intro section container" id="about"><div className="section-marker"><span>01</span><span>ABOUT FELICE</span></div><div className="intro-grid"><div><p className="eyebrow">A QUIET PLACE TO FEEL BETTER</p><h2>一人ひとりに向き合う、<br/>小さなプライベートサロン。</h2></div><div className="intro-text"><p>大塚駅徒歩1分のFeliceです。脱毛・毛穴洗浄・シミケア・よもぎ蒸し・整体を通して、お客様一人ひとりのお悩みに寄り添っています。</p><p>看護師としての経験と、皮膚科勤務で培った知識を活かし、お肌の状態を丁寧に確認しながら施術。完全個室の落ち着いた空間で、美容もリフレッシュもお任せください。</p><p>高額なコース契約はなく、すべて都度払い。ご自身のペースで無理なく通っていただけます。</p></div></div></section>
<section className="reasons section"><div className="container"><div className="section-marker"><span>02</span><span>WHY FELICE</span></div><div className="reasons-head"><p className="eyebrow">THREE REASONS</p><h2>Feliceが選ばれる理由</h2></div><div className="reason reason-one"><div className="reason-photo"><Photo kind="treatment" label="施術"/></div><div className="reason-copy"><span className="reason-number">01 / TRUST</span><h3>安心</h3><p>看護師経験を活かした丁寧なカウンセリングと施術で、初めての方も安心してご利用いただけます。皮膚科勤務経験で培った知識も活かし、お肌のお悩みを確認します。</p></div></div><div className="reason reason-two"><div className="reason-copy"><span className="reason-number">02 / FLEXIBILITY</span><h3>通いやすさ</h3><p>高額なコース契約はなく、すべて都度払い。必要なときに、ご自身のペースで無理なく通っていただけます。</p></div><div className="reason-rule" aria-hidden="true">F</div></div><div className="reason reason-three"><div className="reason-photo"><Photo kind="room" label="店内"/></div><div className="reason-copy"><span className="reason-number">03 / PRIVACY</span><h3>完全個室</h3><p>周りを気にせずゆったり過ごせるプライベート空間。日常から少し離れて、自分のための時間をお過ごしください。</p></div></div></div></section>
<section className="menu-section section"><div className="container"><div className="section-marker"><span>03</span><span>TREATMENTS</span></div><div className="menu-heading"><div><p className="eyebrow">BEAUTY & RELAXATION</p><h2>今日の自分に、<br/>必要なケアを。</h2></div><p>美容とリラクゼーションの多彩なメニューをご用意。施術内容・料金・空き状況はホットペッパービューティーでご確認ください。</p></div><div className="menu-layout"><Photo kind="menu" label="メニュー"/><div className="menu-list">{menu.map((m,i)=><div key={m}><span>0{i+1}</span><strong>{m}</strong><span>↗</span></div>)}<a className="button outline" href={site.hotpepper} target="_blank" rel="noopener noreferrer">メニュー・料金を見る <span>↗</span></a></div></div></div></section>
<section className="therapist-teaser section container"><div className="section-marker"><span>04</span><span>THERAPIST</span></div><div className="therapist-grid"><Photo kind="therapist" label="Feliceオーナー 横田珠里"/><div><p className="eyebrow">A PERSONAL APPROACH</p><h2>安心して話せることから、<br/>施術を始めたい。</h2><p>看護師として、そして皮膚科勤務で得た知識を、目の前のお客様のために。お悩みやご希望を伺い、無理のないケアをご提案します。</p><Link className="text-link" href="/therapist">セラピスト紹介を見る →</Link></div></div></section>
<section className="shop-teaser section"><div className="container shop-grid"><div><div className="section-marker"><span>05</span><span>ACCESS</span></div><p className="eyebrow">OTSUKA, TOKYO</p><h2>駅から徒歩1分。<br/>いつもの街に、静かな場所。</h2><dl><div><dt>住所</dt><dd>〒{site.postal}<br/>{site.address}</dd></div><div><dt>営業時間</dt><dd>{site.hours}（{site.closed}）</dd></div><div><dt>アクセス</dt><dd>{site.access}</dd></div><div><dt>電話番号</dt><dd><a href={`tel:${site.phone}`}>{site.phone}</a></dd></div></dl><Link className="text-link" href="/shop">店舗情報を見る →</Link></div><Photo kind="exterior" label="店舗外観"/></div></section>
<section className="blog-teaser section container"><div className="section-marker"><span>06</span><span>JOURNAL</span></div><div className="blog-head"><div><p className="eyebrow">FROM FELICE</p><h2>ブログ</h2></div><Link className="text-link" href="/blog">ブログ一覧を見る →</Link></div><div className="post-list">{posts.map(p=><Link href={`/blog/${p.slug}`} key={p.id} className="post-row"><time>{p.publishedAt.slice(0,10).replaceAll('-','.')}</time><span>{p.category}</span><strong>{p.title}</strong><b>→</b></Link>)}</div></section><Booking/></>}

